### ISSUE TITLE
Missing num_layers argument for PoseResNet

### ISSUE THREAD

**Issue by penghongkwek** [yingkunwu/hand-gesture-recognition#3]
I am getting the following error.

TypeError: __init__() missing 1 required positional argument: 'num_layers'

Please advise. Thank you

**Comment by yingkunwu** [comment]
Hi, can you provide more detail with the error that you encounter?
For example, can you show at which line the error occurred and that command did you use?

Thanks!

**Comment by penghongkwek** [comment]
The following is the error that I have encountered.

Traceback (most recent call last):
  File "detect.py", line 145, in <module>
    d = Detect(configs)
  File "detect.py", line 25, in __init__
    self.classifier = PoseResNet(nof_joints=self.configs['num_joints'], nof_classes=self.configs['num_classes'])
TypeError: __init__() got an unexpected keyword argument 'nof_joints'

May I know which python version you are using? Are you able to share your requirements.txt file, so that I can refer to the version of each dependency.

Thank you

**Comment by yingkunwu** [comment]
Thank you for reporting the issue. It seems like I did not fix the previous code after I refactor the model.
Now you have to look at the input of the class [here](https://github.com/yingkunwu/hand-gesture-recognition/blob/9a051f613c2f36f56569e20a9b41819bf7d82293/model/poseresnet.py#L10) in order to initialize the model. I can fix this and also provide the requirements.txt file in a few days.

Thanks!

**Comment by penghongkwek** [comment]
Ahhh I see. No problem. Thanks alot:)
